import React from 'react';

interface DisclaimerBannerProps {
  onAccept?: () => void;
  accepted?: boolean;
  showCheckbox?: boolean;
}

export const DisclaimerBanner: React.FC<DisclaimerBannerProps> = ({
  onAccept,
  accepted = false,
  showCheckbox = false,
}) => {
  return (
    <div className="bg-amber-50 border-2 border-amber-400 rounded-lg p-4 my-4 shadow-sm text-slate-900">
      <div className="flex items-start space-x-3">
        <div className="flex-shrink-0 mt-0.5 text-amber-700">
          <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
            <path
              fillRule="evenodd"
              d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z"
              clipRule="evenodd"
            />
          </svg>
        </div>
        <div className="flex-1">
          <div className="flex items-center space-x-2">
            <span className="text-xs font-bold uppercase tracking-wider bg-amber-200 text-amber-900 px-2 py-0.5 rounded">
              Statutory Legal Notice
            </span>
            <span className="text-xs text-amber-800 font-semibold">
              Advocates Act, 1961 & BCI Compliance
            </span>
          </div>
          <p className="mt-2 text-xs leading-relaxed text-slate-800 font-medium">
            <strong>MANDATORY STATUTORY DISCLAIMER:</strong> This structured summary and procedural classification is generated by an automated artificial intelligence system solely to assist citizens and MSMEs in organizing factual dispute narratives. <strong>The AI Case Assistant does NOT provide legal advice, legal opinions, litigation probabilities, or formal legal representation.</strong> No advocate-client privileged relationship is created by utilizing this automated intake utility. Only a verified advocate enrolled with a State Bar Council can provide formal legal advisory upon consultation.
          </p>
          {showCheckbox && (
            <label className="mt-3 flex items-center space-x-2 cursor-pointer pt-2 border-t border-amber-200">
              <input
                type="checkbox"
                checked={accepted}
                onChange={onAccept}
                className="w-4 h-4 text-amber-600 rounded border-amber-400 focus:ring-2 focus:ring-amber-500 cursor-pointer"
              />
              <span className="text-xs font-semibold text-slate-900">
                I understand and acknowledge that this AI summary does not constitute formal legal counsel.
              </span>
            </label>
          )}
        </div>
      </div>
    </div>
  );
};
